### ISSUE TITLE
hi, now do not support Deluge v2?

### ISSUE THREAD

**Issue by kslr** [t3hk0d3/deluge-api#3]
```shell
deluge -v
deluge 2.0b1
libtorrent: 1.1.4.0
Python: 2.7.12
OS: Linux Ubuntu 16.04 xenial
```

```ruby
require 'deluge'

# Initialize client
client = Deluge::Rpc::Client.new(
    host: 'localhost', port: 58846,
    login: 'localclient', password: '9b20625ef11fc963dbc1bee0a1ac9967808d1b20'
)

client.connect
puts client.api_methods
```
```shell
/var/lib/gems/2.3.0/gems/deluge-rpc-0.1.3/lib/deluge/rpc/connection.rb:105:in `call': Failed to retreive response for 'daemon.login' in 5.0 seconds. Probably method not exists. (Deluge::Rpc::Connection::InvokeTimeoutError)
	from /var/lib/gems/2.3.0/gems/deluge-rpc-0.1.3/lib/deluge/rpc/connection.rb:65:in `authenticate'
	from /var/lib/gems/2.3.0/gems/deluge-rpc-0.1.3/lib/deluge/rpc/client.rb:18:in `connect'
	from test.rb:9:in `<main>'
```

rouble to help me look

**Comment by t3hk0d3** [comment]
@kslr 2 years later, but Deluge 2.0+ support was just added 😂

**Comment by kslr** [comment]
![sticker](https://user-images.githubusercontent.com/5516323/91638289-edffeb00-ea40-11ea-84ea-98c2d70efb1d.png)

~4years, This is good news, thanks work
