### ISSUE TITLE
Deluge::Rpc::Connection::RPCError (IncompatibleClient)

### ISSUE THREAD

**Issue by acavalin** [t3hk0d3/deluge-api#4]
Hello,

I'm unable to connect to deluge 2, I get this error upon connection:

~~~
Traceback (most recent call last):
        8: from /usr/bin/irb:23:in `<main>'
        7: from /usr/bin/irb:23:in `load'
        6: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        5: from (irb):7
        4: from /home/cloud/.gem/ruby/2.7.0/gems/deluge-rpc-0.2.0/lib/deluge/rpc/client.rb:18:in `connect'
        3: from /home/cloud/.gem/ruby/2.7.0/gems/deluge-rpc-0.2.0/lib/deluge/rpc/connection.rb:70:in `authenticate'
        2: from /home/cloud/.gem/ruby/2.7.0/gems/deluge-rpc-0.2.0/lib/deluge/rpc/connection.rb:107:in `call'
        1: from /home/cloud/.gem/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/concern/obligation.rb:101:in `value!'
Deluge::Rpc::Connection::RPCError (IncompatibleClient)
~~~

this is the sample code I used:

~~~ruby
require 'deluge'

client = Deluge::Rpc::Client.new \
  host: 'localhost', port: 58846,
  login: 'myuser', password: 'mypass'

client.connect
~~~

These are my system specs:

* `uname -ra` => Linux raoul 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux
* `cat /etc/debian_version` => 11.2
*  `ruby --version` => ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [arm-linux-gnueabihf]
* `deluged --version`
   ~~~
   deluged 2.0.3
   libtorrent: 1.2.9.0
   Python: 3.9.2
   OS: Linux Raspbian GNU/Linux 11 bullseye
   ~~~

Can you help me?

**Comment by acavalin** [comment]
I found a solution: now with version 2 the `client_version` argument [is mandatory](https://github.com/gdm85/go-libdeluge/blob/643e583c90f8419cd35c65a9f700a156e8d8753a/delugeclient.go#L516).

Just add this line within lib/deluge/rpc/connection.rb in `def call` [method](https://github.com/t3hk0d3/deluge-rpc/blob/5b43d5f976379ea5c9fd4786ac184c88dd448b59/lib/deluge/rpc/connection.rb#L97):
~~~ruby
kwargs['client_version'] = Deluge::Rpc::VERSION.to_s if method == 'daemon.login'
~~~
